### ISSUE TITLE
Ubuntu 24.04.3 LTS must apt install libcap-dev add #include <utime.h>

### ISSUE THREAD

**Issue by caozhzh** [Ferki-git-creator/ferki-escalator#1]
When compile on Ubuntu 24.04.3 LTS, two errors got
1.
linux_escalator.c:25:10: fatal error: sys/capability.h: No such file or directory
   25 | #include <sys/capability.h>
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.

this error can be solved by `sudo apt install libcap-dev`
2.
linux_escalator.c:25:10: fatal error: sys/capability.h: No such file or directory
   25 | #include <sys/capability.h>
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
this error can be solved by add #include <utime.h> in linux_escalator.c

**Comment by Ferki-git-creator** [comment]
First of all, why is this an issue if you already know which dependencies to install? You should be able to handle your environment. Secondly, I'm planning to implement a custom version that doesn't rely on this library at all to keep it truly dependency-free. Thanks for the feedback anyway.

**Comment by caozhzh** [comment]
I'm sorry for submitting an unnecessary issue, but I can't delete it now.

**Comment by Ferki-git-creator** [comment]
But I don’t mind. Im generally pleased to have at least one issue, because in most of my other repositories I have zero.
And your feedback became the motivation to make my tool without this library and to implement my own solution. The parts I need are already right in the code.
A new commit is coming soon.

**Comment by Ferki-git-creator** [comment]
❗❗❗Done! I've just pushed version 1.1. >
I’ve completely removed the dependency on libcap and switched to a custom, library-free implementation. Now the tool is fully standalone and should compile on your Ubuntu 24.04 (and other architectures) without any extra packages or headers.
You can find the detailed technical breakdown in the latest commit description
Please pull the changes and let me know if it works for you. I hope you can now fully use the tool for your own goals, whatever they may be 😈/😇.
Feel free to close the issue if everything is okay!❗❗❗

**Comment by Ferki-git-creator** [comment]
Well, I think the problem is gone, so I'll close this issue.
